---
title: "Chapter 3 - Figures"
author: "Brendan"
date: "14/04/2021"
output: word_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
# Installed and loaded dplyr as a google search said this was related to %>% not being found. Seemed to solve the issue:
library(tidyverse)
library(car)
library(sciplot)
library(ggplot2)
library(lme4)
library(emmeans)
library(corrplot)
library(ggpubr)
library(visreg)
library(raster)
library(sp)
library(spdep)
library(spatialreg)
library(dplyr)

dat <- read.csv("Data/BASE_brendan_20201008.tsv", sep = "\t")

dat$order <- as.factor(dat$order)
dat$guild <- as.factor(dat$guild)
dat$Sample.ID <- as.factor(dat$Sample.ID)
#str(dat)
#table(dat$guild)
#table(dat$vegetation_type)
#table(dat$broad_land_use)

datf50 <- dat %>% 
  filter(depth_cm == 0 & order %in% c('Glomerales', 'Gigasporales') & vegetation_type %in% c('Forest','Grassland','Woodland') & p.colwell_mgkg < 50 & n.no3_mgkg <= 50 & n.nh4_mgkg <= 50) %>% 
  mutate(relabund = OTU.Count/seqdepth) %>% 
  mutate(NH4NO3Rat = n.nh4_mgkg/n.no3_mgkg) %>%
  mutate(NH4PRat = n.nh4_mgkg/p.colwell_mgkg) %>%
  mutate(NO3PRat = n.no3_mgkg/p.colwell_mgkg) %>%
  group_by(Sample.ID, order) %>% 
  summarise(relabund = sum(relabund),
  #summarise(relabund = mean(relabund),
            lon = lon[1],
            lat = lat[1],
            p.colwell_mgkg = mean(p.colwell_mgkg), 
            n.nh4_mgkg = mean(n.nh4_mgkg),
            n.no3_mgkg = mean(n.no3_mgkg),
            NH4NO3Rat = mean(NH4NO3Rat),
            NH4PRat = mean(NH4PRat),
            NO3PRat = mean(NO3PRat),
            vegetation_type = vegetation_type[1], 
            broad_land_use = broad_land_use[1]) %>% 
  # add rows and zero values where taxa are missing
  pivot_wider(names_from=order, values_from=relabund, values_fill=0) %>% 
  pivot_longer(cols=any_of(unique(dat$order)), names_to='order', values_to='relabund')

datf50$log_relabund <- log10(datf50$relabund+0.000001)
datf50$log_p <- log10(datf50$p.colwell_mgkg+0.000001)
datf50$log_NO3PRat <- log10(datf50$NO3PRat+0.000001)
datf50$log_NH4PRat <- log10(datf50$NH4PRat+0.000001)
datf50$log_no3 <- log10(datf50$n.no3_mgkg+0.000001)
datf50$log_nh4 <- log10(datf50$n.nh4_mgkg+0.000001)
datf50$logNH4logPRatio <- datf50$log_nh4 / datf50$log_p
datf50$logNO3logPRatio <- datf50$log_no3 / datf50$log_p

datf50$vegetation_type <- factor(datf50$vegetation_type, levels = c("Grassland","Woodland","Forest"))
datf50$order <- factor(datf50$order, levels = c("Gigasporales", "Glomerales"))
levels(datf50$order)[levels(datf50$order)=="Glomerales"] <- "Glomeraceae"
levels(datf50$order)[levels(datf50$order)=="Gigasporales"] <- "Gigasporaceae"

levels(datf50$order)
table(datf50$order)
table(datf50$vegetation_type)


```

# Figure 2

## Soil Phosphorus (50 mg/kg)

```{r Soil P 50, include = TRUE, echo = FALSE}

datplot <- datf50 
datplot <- datplot %>% 
  mutate_at("order", str_replace, "Glomerales", "Glomeraceae") %>%
  mutate_at("order", str_replace, "Gigasporales", "Gigasporaceae") 

ggplot(datplot, aes(x=log_p, y=log_relabund, col=order)) +
# ggplot(datfveg, aes(x=p.colwell_mgkg, y=log10(relabund+0.000001), col=order)) + 
#  stat_smooth(method='lm', formula = y ~ x + I(x^2), aes(fill=order), fullrange=T, show.legend=F) +
  stat_smooth(method='lm', formula = y ~ x + I(x), aes(fill=order), fullrange=T, show.legend=F) +
  geom_point() + 
  ylab('Relative Abundance log10(%)') + xlab('Phosphate-P concentration log10(mg/kg)') + 
  scale_fill_manual(values=c('red', 'blue'), name=NULL) +
  scale_color_manual(values=c('red', 'blue'), name=NULL) + 
  facet_grid(rows=vars(order)) + 
  theme_bw() + 
  theme(legend.position='top')

ggsave("figures/figure2.pdf", plot = last_plot(), device = pdf, 
       width=4, height=5)

```

# Figure 3

## Soil Phosphorus (50 mg/kg)
```{r Soil P 50, include = TRUE, echo = FALSE}

ggplot(datf50, aes(x=log_p, y=log_relabund)) + 
  stat_smooth(method='lm', aes(fill=order), fullrange=T, show.legend=F) +
  geom_point() + 
  ylab('Relative Abundance log10(%)') + xlab('Phosphorus concentration log10(mg/kg)') + 
  scale_fill_manual(values=c('red', 'blue')) +
  scale_color_manual(values=c('red', 'blue')) + 
  facet_grid(rows=vars(order)) + 
  theme_bw()

## Comparison of the Gigasporaceae and Glomeraceae relative abundance over soil P, split by vegetation type:
pfigv <- ggplot(datf50, aes(x=log_p, y=log_relabund, col=order)) +
  stat_smooth(method='lm', formula = y ~ x, aes(fill=order), fullrange=T, show.legend=F) +
  geom_point() + 
  ylab('Relative Abundance log10(%)') + xlab('Phosphate-P concentration\nlog10(mg/kg)') + 
  scale_fill_manual(values=c('red', 'blue'), name=NULL) +
  scale_color_manual(values=c('red', 'blue'), name=NULL) + 
  facet_grid(rows=vars(vegetation_type)) + 
  theme_bw()

pfigv

```

\newpage
## Soil Ammonium (NH4 - 50 mg/kg)
```{r Soil NH4 50, include= TRUE, echo = FALSE}

## Comparison of the Gigasporaceae and Glomeraceae relative abundance over soil NH4 using transformed nitrogen data: 
ggplot(datf50, aes(x=log_nh4, y=log_relabund)) + 
  stat_smooth(method='lm', aes(fill=order), fullrange=T, show.legend=F) +
  geom_point() + 
  ylab('Relative Abundance log10(%)') + xlab('NH4 concentration log10(mg/kg)') + 
  scale_fill_manual(values=c('red', 'blue')) +
  scale_color_manual(values=c('red', 'blue')) + 
  facet_grid(rows=vars(order)) + 
  theme_bw()


## Comparison of the Gigasporaceae and Glomeraceae relative abundance over soil NH4, split by vegetation type:
nh4figv <- ggplot(datf50, aes(x=log_nh4, y=log_relabund, col=order)) +
  stat_smooth(method='lm', formula = y ~ x, aes(fill=order), fullrange=T, show.legend=F) +
  geom_point() + 
  ylab('') + xlab('Ammonium-N concentration\nlog10(mg/kg)') + 
  scale_fill_manual(values=c('red', 'blue'), name=NULL) +
  scale_color_manual(values=c('red', 'blue'), name=NULL) + 
  facet_grid(rows=vars(vegetation_type)) + 
  theme_bw()

nh4figv
```

## Soil Nitrate (NO3 - 50 mg/kg)
```{r Soil NO3 50, include= TRUE, echo = FALSE}

## Comparison of the Gigasporaceae and Glomeraceae relative abundance over soil NO3: 

ggplot(datf50, aes(x=log_no3, y=log_relabund)) + 
  stat_smooth(method='lm', formula = y ~ x + I(x^2), aes(fill=order), fullrange=T, show.legend=F) +
  geom_point() + 
  ylab('Relative Abundance') + xlab('NO3 concentration log10(mg/kg)') + 
  scale_fill_manual(values=c('red', 'blue')) +
  scale_color_manual(values=c('red', 'blue')) + 
  facet_grid(rows=vars(order)) + 
  theme_bw()

## Comparison of the Gigasporaceae and Glomeraceae relative abundance over soil NH4, split by vegetation type:
no3figv <- ggplot(datf50, aes(x=log_no3, y=log_relabund, col=order)) +
  stat_smooth(method='lm', formula = y ~ x + I(x^2), aes(fill=order), fullrange=T, show.legend=F) +
  geom_point() + 
  ylab('') + xlab('Nitrate-N concentration\nlog10(mg/kg)') + 
  scale_fill_manual(values=c('red', 'blue'), name=NULL) +
  scale_color_manual(values=c('red', 'blue'), name=NULL) + 
  facet_grid(rows=vars(vegetation_type)) + 
  theme_bw()

no3figv
```

## Combined figures
```{r combined figures, include= TRUE, echo = FALSE}
library(tidyverse)
library("ggpubr")

vfig <- ggarrange(pfigv, no3figv, nh4figv,
                    ncol = 3, nrow = 1,
                    common.legend = TRUE,
                    legend = "top", 
                  labels='AUTO') +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(), legend.title=element_blank())
vfig
ggsave("figures/figure3.pdf", plot = last_plot(), device = pdf, 
       width=10, height=8)
```

